  #https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
server.port: 8080
spring:
  application:
    name: photoapp
    jackson:
      default-property-inclusion: non_null
  servlet:
        multipart.enabled: true

photoapp.file:
    defaultPath: c:\up-dir

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}